---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev
  working_directory: /srv

version: 2
jobs:
  test-build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install && bundle install
      - run:
          name: Build the site resources
          command: jekyll build
      - run:
          name: Run the site server
          command: jekyll serve
          background: true
      - run:
          name: Check site is accessible
          command: sleep 1 && curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://127.0.0.1:4000/practices/
  check-prettier:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Prettier over all files
          command: prettier-check **/*
workflows:
  version: 2
  build:
    jobs:
      - test-build
      - check-prettier
